# サイト設定
title: "福井県透析患者災害時対策マニュアル"
description: "福井県内の透析患者とその家族、医療従事者のための災害時対応マニュアル"
url: "https://fukuitouseki.com"

# Jekyll設定
markdown: kramdown
highlighter: rouge
theme: minima

# プラグイン
plugins:
  - jekyll-feed
  - jekyll-sitemap

# ビルド設定
source: .
destination: ./_site
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

# ナビゲーション
header_pages:
  - docs/index.md

# その他
timezone: Asia/Tokyo
lang: ja
