project:
  type: website
  output-dir: _site
  render: 
    - "*.qmd"

# プロジェクト全体設定  
lang: ja-JP
timezone: "Asia/Tokyo"

website:
  title: "福井県透析患者災害時対策マニュアル"
  description: "福井県内の透析患者とその家族、医療従事者のための災害時対応マニュアル"
  site-url: "https://fukuitouseki.com"
  
  navbar:
    title: "福井県透析防災マニュアル"
    left:
      - href: index.qmd
        text: "ホーム"
      - text: "マニュアル本体"
        menu:
          - href: docs/0100_各施設の役割と対応.qmd
            text: "各施設の役割と対応"
          - href: docs/0200_福井県透析施設ネットワークの役割と対応.qmd
            text: "ネットワークの役割と対応"
      - text: "チェックシート"
        menu:
          - href: docs/index.qmd
            text: "様式・チェックシート一覧"
          - text: "初動対応（0-24時間）"
          - href: docs/1410_初動対応チェックシート_0-30分.qmd
            text: "0-30分チェックシート"
          - href: docs/1420_初動対応チェックシート_1-3時間.qmd
            text: "1-3時間チェックシート" 
          - href: docs/1430_初動対応チェックシート_3-24時間.qmd
            text: "3-24時間チェックシート"

format:
  html:
    theme: 
      - cosmo
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: left
    number-sections: true
    smooth-scroll: true
    lang: ja
    mainfont: "Noto Sans CJK JP, 'Hiragino Sans', 'Hiragino Kaku Gothic ProN', Meiryo, sans-serif"
    code-copy: true
    anchor-sections: true
    link-external-newwindow: true

# PDF設定を無効化してHTMLのみレンダリング  
execute:
  freeze: auto