project:
  type: book
  output-dir: booklet-pdf

book:
  title: "福井県透析防災マニュアル"
  author: "福井透析ネットワーク本部"
  date: today
  language: ja
  
  chapters:
    - index.qmd
    - docs/0100_各施設の役割と対応.qmd
    - docs/0200_福井県透析施設ネットワークの役割と対応.qmd
    - docs/1320_備蓄物資点検チェックシート.qmd
    - docs/1330_患者緊急連絡先チェックシート.qmd
    - docs/1410_初動対応チェックシート_0-30分.qmd
    - docs/1420_初動対応チェックシート_1-3時間.qmd
    - docs/1430_初動対応チェックシート_3-24時間.qmd
    - docs/1440_災害時透析医療機関状況報告書_初動報告用.qmd
    - docs/1450_スタッフ安否確認表.qmd
    - docs/1451_患者安全確認表.qmd
    - docs/9910_公的防災情報リンク集.qmd
    - docs/9920_福井県内透析施設一覧.qmd
    - docs/9930_透析患者向け食品栄養成分表.qmd

format:
  pdf:
    pdf-engine: xelatex
    documentclass: scrbook
    lang: ja
    fontsize: 11pt
    geometry:
      - top=25mm
      - bottom=25mm
      - left=20mm
      - right=20mm
    toc: true
    toc-depth: 2
    number-sections: true