---
title: "備蓄物資点検チェックシート（平時の準備）"
subtitle: "212 備蓄物資点検チェックシート（平時の準備）"
date: "2025-09-08"
format: 
  html:
    toc: true
    toc-depth: 3
    number-sections: true
    css: custom.css
  pdf:
    documentclass: jarticle
    geometry: 
      - top=30mm
      - bottom=30mm  
      - left=20mm
      - right=20mm
      - footskip=18mm
      - headsep=12mm
    include-in-header:
      - text: |
          \usepackage{setspace}
          \setstretch{1.3}
          \usepackage{array}
          \usepackage{longtable}
          \usepackage{amssymb}
          \usepackage{multirow}
          \usepackage{booktabs}
          \newcommand{\checkbox}{$\square$\ }
          \newcommand{\checkedbox}{$\blacksquare$\ }
          \newcommand{\underlinespace}[1]{\underline{\hspace{#1}}}
          \newcommand{\circlecheck}{$\bigcirc$\ }
lang: ja
version: "2025.09.06版"
header-right: "212 備蓄物資点検チェックシート（平時の準備） 2025.09.06版"
---

% 手動でタイトルを作成

{\Large**備蓄物資点検チェックシート（平時の準備）**}



**施設名：** \underlinespace{8cm}



**点検実施者：** \underlinespace{4cm}      **点検日：** \underlinespace{3cm}



**点検責任者：** \underlinespace{4cm}      **確認日：** \underlinespace{3cm}



% 透析関連器材の備蓄

**\large 透析関連器材の備蓄状況**




\begin{longtable}{|p{3.5cm}|p{2cm}|p{2cm}|p{1.8cm}|p{2cm}|}
\hline
**物品名** & **通常在庫** & **備蓄数量** & **使用期限** & **状態** \\
\hline
\endfirsthead
\hline
**物品名** & **通常在庫** & **備蓄数量** & **使用期限** & **状態** \\
\hline
\endhead
ダイアライザー & \underlinespace{1.5cm} & \underlinespace{1.5cm} & \underlinespace{1.3cm} & \checkbox 良好 \checkbox 要交換 \\[0.5cm]
\hline
回路セット & \underlinespace{1.5cm} & \underlinespace{1.5cm} & \underlinespace{1.3cm} & \checkbox 良好 \checkbox 要交換 \\[0.5cm]
\hline
透析液（A液） & \underlinespace{1.3cm}L & \underlinespace{1.3cm}L & \underlinespace{1.3cm} & \checkbox 良好 \checkbox 要交換 \\[0.5cm]
\hline
透析液（B液） & \underlinespace{1.3cm}L & \underlinespace{1.3cm}L & \underlinespace{1.3cm} & \checkbox 良好 \checkbox 要交換 \\[0.5cm]
\hline
生理食塩水 & \underlinespace{1.5cm} & \underlinespace{1.5cm} & \underlinespace{1.3cm} & \checkbox 良好 \checkbox 要交換 \\[0.5cm]
\hline
穿刺針 & \underlinespace{1.5cm} & \underlinespace{1.5cm} & \underlinespace{1.3cm} & \checkbox 良好 \checkbox 要交換 \\[0.5cm]
\hline
透析用カテーテル & \underlinespace{1.5cm} & \underlinespace{1.5cm} & \underlinespace{1.3cm} & \checkbox 良好 \checkbox 要交換 \\[0.5cm]
\hline
\end{longtable}

% 医薬品の備蓄

**\large 透析関連医薬品の備蓄状況**




\begin{longtable}{|p{3.5cm}|p{2cm}|p{2cm}|p{1.8cm}|p{2cm}|}
\hline
**医薬品名** & **通常在庫** & **備蓄数量** & **使用期限** & **状態** \\
\hline
\endfirsthead
\hline
**医薬品名** & **通常在庫** & **備蓄数量** & **使用期限** & **状態** \\
\hline
\endhead
ヘパリン & \underlinespace{1.5cm} & \underlinespace{1.5cm} & \underlinespace{1.3cm} & \checkbox 良好 \checkbox 要交換 \\[0.5cm]
\hline
エポジン & \underlinespace{1.5cm} & \underlinespace{1.5cm} & \underlinespace{1.3cm} & \checkbox 良好 \checkbox 要交換 \\[0.5cm]
\hline
降圧剤 & \underlinespace{1.5cm} & \underlinespace{1.5cm} & \underlinespace{1.3cm} & \checkbox 良好 \checkbox 要交換 \\[0.5cm]
\hline
昇圧剤 & \underlinespace{1.5cm} & \underlinespace{1.5cm} & \underlinespace{1.3cm} & \checkbox 良好 \checkbox 要交換 \\[0.5cm]
\hline
抗痙攣剤 & \underlinespace{1.5cm} & \underlinespace{1.5cm} & \underlinespace{1.3cm} & \checkbox 良好 \checkbox 要交換 \\[0.5cm]
\hline
緊急薬剤 & \underlinespace{1.5cm} & \underlinespace{1.5cm} & \underlinespace{1.3cm} & \checkbox 良好 \checkbox 要交換 \\[0.5cm]
\hline
その他 & \underlinespace{1.5cm} & \underlinespace{1.5cm} & \underlinespace{1.3cm} & \checkbox 良好 \checkbox 要交換 \\[0.5cm]
\hline
\end{longtable}

% ライフライン関連備蓄

**\large ライフライン関連備蓄状況**




\checkbox 電力関連：



\checkbox 自家発電用燃料：\underlinespace{3cm}L （\underlinespace{2cm}時間分）



\checkbox バッテリー：\checkbox 充電済      予備バッテリー：\underlinespace{2cm}個



\checkbox 水関連：



\checkbox 透析用水：貯水量\underlinespace{3cm}m$^3$ （\underlinespace{2cm}日分）



\checkbox 飲料水：\underlinespace{3cm}L （\underlinespace{2cm}日分）



\checkbox 食料関連：



\checkbox スタッフ用食料：\underlinespace{3cm}食分 （\underlinespace{2cm}日分）



\checkbox 患者用補食：\underlinespace{3cm}食分



% 通信・情報機器の備蓄

**\large 通信・情報機器の備蓄状況**




\begin{longtable}{|p{4cm}|p{2cm}|p{2cm}|p{3.5cm}|}
\hline
**機器名** & **数量** & **動作確認** & **備考** \\
\hline
携帯電話・スマートフォン & \underlinespace{1.5cm} & \checkbox 良好 & \\[0.5cm]
\hline
衛星電話 & \underlinespace{1.5cm} & \checkbox 良好 & \\[0.5cm]
\hline
携帯ラジオ & \underlinespace{1.5cm} & \checkbox 良好 & \\[0.5cm]
\hline
携帯テレビ & \underlinespace{1.5cm} & \checkbox 良好 & \\[0.5cm]
\hline
懐中電灯 & \underlinespace{1.5cm} & \checkbox 良好 & \\[0.5cm]
\hline
ランタン & \underlinespace{1.5cm} & \checkbox 良好 & \\[0.5cm]
\hline
ハンドマイク & \underlinespace{1.5cm} & \checkbox 良好 & \\[0.5cm]
\hline
\end{longtable}

% 業者調達体制の確認

**\large 業者調達体制の確認**




\checkbox 透析器材業者との災害時調達協定：\checkbox 締結済      \checkbox 要締結



連絡先確認：\checkbox 確認済      担当者：\underlinespace{6cm}



\checkbox 医薬品業者との災害時調達協定：\checkbox 締結済      \checkbox 要締結



連絡先確認：\checkbox 確認済      担当者：\underlinespace{6cm}



\checkbox 食料業者との災害時調達協定：\checkbox 締結済      \checkbox 要締結



連絡先確認：\checkbox 確認済      担当者：\underlinespace{6cm}



\checkbox 燃料業者との災害時調達協定：\checkbox 締結済      \checkbox 要締結



連絡先確認：\checkbox 確認済      担当者：\underlinespace{6cm}



% 改善事項・次回点検予定

**\large 改善事項・次回点検予定**




**要改善・補充事項：**



1. \underlinespace{12cm}



2. \underlinespace{12cm}



3. \underlinespace{12cm}



**次回点検予定日：** \underlinespace{4cm}      **実施予定者：** \underlinespace{4cm}



**点検責任者確認：** \underlinespace{4cm}      **確認印：** \underlinespace{3cm}