---
title: "様式07"
subtitle: "117 様式07"
date: "2025-09-08"
format: 
  html:
    toc: true
    toc-depth: 3
    number-sections: true
    css: custom.css
  pdf:
    documentclass: jarticle
    geometry: 
      - top=30mm
      - bottom=30mm  
      - left=20mm
      - right=20mm
      - footskip=18mm
      - headsep=12mm
    include-in-header:
      - text: |
          \usepackage{setspace}
          \setstretch{1.3}
          \usepackage{array}
          \usepackage{longtable}
          \usepackage{amssymb}
          \usepackage{multirow}
          \usepackage{booktabs}
          \newcommand{\checkbox}{$\square$\ }
          \newcommand{\checkedbox}{$\blacksquare$\ }
          \newcommand{\underlinespace}[1]{\underline{\hspace{#1}}}
          \newcommand{\circlecheck}{$\bigcirc$\ }
lang: ja
version: "2025.09.06版"
header-right: "117 様式07 2025.09.06版"
---

% 手動でタイトルを作成

{\Large**様式07**}\\

{\Large**物資薬剤備蓄状況確認表**}



**【確認日時】**\underlinespace{2cm}年\underlinespace{1cm}月\underlinespace{1cm}日\underlinespace{1cm}時\underlinespace{1cm}分



**【施設名】** \underlinespace{10cm}



**【確認者】** \underlinespace{10cm}



% 透析用物資

**\large 透析用物資**




\begin{longtable}{|p{3.5cm}|p{2.5cm}|p{2.5cm}|p{2.5cm}|p{2.5cm}|}
\hline
**品目** & **現在庫数** & **通常消費/日** & **使用可能日数** & **備考** \\
\hline
\endfirsthead

\hline
**品目** & **現在庫数** & **通常消費/日** & **使用可能日数** & **備考** \\
\hline
\endhead

透析液（HD用） &  &  &  &  \\
\hline
透析液（HDF用） &  &  &  &  \\
\hline
ダイアライザー &  &  &  &  \\
\hline
回路セット &  &  &  &  \\
\hline
穿刺針 &  &  &  &  \\
\hline
点滴セット &  &  &  &  \\
\hline
シリンジ &  &  &  &  \\
\hline
消毒液 &  &  &  &  \\
\hline
ガーゼ・綿球 &  &  &  &  \\
\hline
テープ類 &  &  &  &  \\
\hline
\end{longtable}



% 薬剤

**\large 薬剤**




\begin{longtable}{|p{3.5cm}|p{2.5cm}|p{2.5cm}|p{2.5cm}|p{2.5cm}|}
\hline
**薬剤名** & **現在庫数** & **通常消費/日** & **使用可能日数** & **備考** \\
\hline
\endfirsthead

\hline
**薬剤名** & **現在庫数** & **通常消費/日** & **使用可能日数** & **備考** \\
\hline
\endhead

ヘパリン &  &  &  &  \\
\hline
エポエチン &  &  &  &  \\
\hline
炭酸水素ナトリウム &  &  &  &  \\
\hline
塩化カルシウム &  &  &  &  \\
\hline
生理食塩水 &  &  &  &  \\
\hline
ブドウ糖液 &  &  &  &  \\
\hline
昇圧剤 &  &  &  &  \\
\hline
降圧剤 &  &  &  &  \\
\hline
緊急薬品セット &  &  &  &  \\
\hline
\end{longtable}



% 緊急時物資

**\large 緊急時物資**




\checkbox 非常用電源燃料：     \checkbox 満タン      /      \checkbox 3/4      /      \checkbox 半分      /      \checkbox 1/4      /      \checkbox 残りわずか



\checkbox 飲料水：     \checkbox 十分（\underlinespace{2cm}L）      /      \checkbox 不足      /      \checkbox なし



\checkbox 非常食：     \checkbox 十分（\underlinespace{2cm}日分）      /      \checkbox 不足      /      \checkbox なし



\checkbox 毛布・寝具：     \checkbox 十分（\underlinespace{2cm}枚）      /      \checkbox 不足      /      \checkbox なし



\checkbox 懐中電灯・電池：     \checkbox 十分      /      \checkbox 不足      /      \checkbox なし



\checkbox ラジオ・通信機器：     \checkbox 正常      /      \checkbox 不具合      /      \checkbox なし



% PD関連物資

**\large PD関連物資（該当施設のみ）**




\checkbox PD透析液：     \checkbox 十分（\underlinespace{2cm}袋）      /      \checkbox 不足      /      \checkbox なし



\checkbox PD回路・バッグ：     \checkbox 十分（\underlinespace{2cm}セット）      /      \checkbox 不足      /      \checkbox なし



\checkbox PD消毒液：     \checkbox 十分      /      \checkbox 不足      /      \checkbox なし



% 保管状況

**\large 保管状況**




\checkbox 薬品冷蔵庫：     \checkbox 正常稼働      /      \checkbox 故障      /      \checkbox 停電



\checkbox 倉庫・保管庫：     \checkbox 正常      /      \checkbox 一部損傷      /      \checkbox 重大損傷



\checkbox 物資の損傷：     \checkbox なし      /      \checkbox 軽微      /      \checkbox 重大



\checkbox 温度管理：     \checkbox 適正      /      \checkbox 要注意      /      \checkbox 不適



% 緊急調達必要物資

**\large 緊急調達必要物資**




\checkbox 最優先：\underlinespace{10cm}



\checkbox 24時間以内：\underlinespace{10cm}



\checkbox 3日以内：\underlinespace{10cm}



% 消費ペース計算

**\large 消費ペース計算**




\checkbox 通常透析継続の場合：\underlinespace{2cm}日間継続可能



\checkbox 短時間透析実施の場合：\underlinespace{2cm}日間継続可能



\checkbox 最小限透析実施の場合：\underlinespace{2cm}日間継続可能



% 特記事項・詳細

**\large 特記事項・詳細**




\underlinespace{13cm}



\underlinespace{13cm}



\underlinespace{13cm}



\underlinespace{13cm}



\underlinespace{13cm}