---
title: "様式07"
subtitle: "117 様式07"
filename: "1322_物資薬剤備蓄状況確認表.qmd"
date-modified: "2025-09-09"
date: "2025-09-08"
format: 
  html:
    toc: true
    toc-depth: 3
    number-sections: true
    css: custom.css
  pdf:
    documentclass: jarticle
    geometry: 
      - top=30mm
      - bottom=30mm  
      - left=20mm
      - right=20mm
      - footskip=18mm
      - headsep=12mm
    include-in-header:
      - text: |
          \usepackage{setspace}
          \setstretch{1.3}
          \usepackage{array}
          \usepackage{longtable}
          \usepackage{amssymb}
          \usepackage{multirow}
          \usepackage{booktabs}
          \newcommand{\checkbox}{$\square$\ }
          \newcommand{\checkedbox}{$\blacksquare$\ }
          \newcommand{\underlinespace}[1]{\underline{\hspace{#1}}}
          \newcommand{\circlecheck}{$\bigcirc$\ }
lang: ja
version: "2025.09.06版"
header-right: "117 様式07 2025.09.06版"
---


# 様式07: 物資薬剤備蓄状況確認表



**【確認日時】**_______年____月____日____時____分



**【施設名】** __________________________________



**【確認者】** __________________________________




## 透析用物資




\begin{longtable}{|p{3.5cm}|p{2.5cm}|p{2.5cm}|p{2.5cm}|p{2.5cm}|}
\hline
**品目** & **現在庫数** & **通常消費/日** & **使用可能日数** & **備考** \\
\hline
\endfirsthead

\hline
**品目** & **現在庫数** & **通常消費/日** & **使用可能日数** & **備考** \\
\hline
\endhead

透析液（HD用） &  &  &  &  \\
\hline
透析液（HDF用） &  &  &  &  \\
\hline
ダイアライザー &  &  &  &  \\
\hline
回路セット &  &  &  &  \\
\hline
穿刺針 &  &  &  &  \\
\hline
点滴セット &  &  &  &  \\
\hline
シリンジ &  &  &  &  \\
\hline
消毒液 &  &  &  &  \\
\hline
ガーゼ・綿球 &  &  &  &  \\
\hline
テープ類 &  &  &  &  \\
\hline
\end{longtable}




## 薬剤




\begin{longtable}{|p{3.5cm}|p{2.5cm}|p{2.5cm}|p{2.5cm}|p{2.5cm}|}
\hline
**薬剤名** & **現在庫数** & **通常消費/日** & **使用可能日数** & **備考** \\
\hline
\endfirsthead

\hline
**薬剤名** & **現在庫数** & **通常消費/日** & **使用可能日数** & **備考** \\
\hline
\endhead

ヘパリン &  &  &  &  \\
\hline
エポエチン &  &  &  &  \\
\hline
炭酸水素ナトリウム &  &  &  &  \\
\hline
塩化カルシウム &  &  &  &  \\
\hline
生理食塩水 &  &  &  &  \\
\hline
ブドウ糖液 &  &  &  &  \\
\hline
昇圧剤 &  &  &  &  \\
\hline
降圧剤 &  &  &  &  \\
\hline
緊急薬品セット &  &  &  &  \\
\hline
\end{longtable}




## 緊急時物資




☐ 非常用電源燃料：     ☐ 満タン      /      ☐ 3/4      /      ☐ 半分      /      ☐ 1/4      /      ☐ 残りわずか



☐ 飲料水：     ☐ 十分（_______L）      /      ☐ 不足      /      ☐ なし



☐ 非常食：     ☐ 十分（_______日分）      /      ☐ 不足      /      ☐ なし



☐ 毛布・寝具：     ☐ 十分（_______枚）      /      ☐ 不足      /      ☐ なし



☐ 懐中電灯・電池：     ☐ 十分      /      ☐ 不足      /      ☐ なし



☐ ラジオ・通信機器：     ☐ 正常      /      ☐ 不具合      /      ☐ なし




## PD関連物資（該当施設のみ）




☐ PD透析液：     ☐ 十分（_______袋）      /      ☐ 不足      /      ☐ なし



☐ PD回路・バッグ：     ☐ 十分（_______セット）      /      ☐ 不足      /      ☐ なし



☐ PD消毒液：     ☐ 十分      /      ☐ 不足      /      ☐ なし




## 保管状況




☐ 薬品冷蔵庫：     ☐ 正常稼働      /      ☐ 故障      /      ☐ 停電



☐ 倉庫・保管庫：     ☐ 正常      /      ☐ 一部損傷      /      ☐ 重大損傷



☐ 物資の損傷：     ☐ なし      /      ☐ 軽微      /      ☐ 重大



☐ 温度管理：     ☐ 適正      /      ☐ 要注意      /      ☐ 不適




## 緊急調達必要物資




☐ 最優先：__________________________________



☐ 24時間以内：__________________________________



☐ 3日以内：__________________________________




## 消費ペース計算




☐ 通常透析継続の場合：_______日間継続可能



☐ 短時間透析実施の場合：_______日間継続可能



☐ 最小限透析実施の場合：_______日間継続可能




## 特記事項・詳細




_____________________________________________



_____________________________________________



_____________________________________________



_____________________________________________



_____________________________________________