---
title: "様式04"
subtitle: "114 様式04"
filename: "1451_患者安全確認表.qmd"
date-modified: "2025-09-09"
date: "2025-09-08"
format: 
  html:
    toc: true
    toc-depth: 3
    number-sections: true
    css: custom.css
  pdf:
    documentclass: jarticle
    geometry: 
      - top=30mm
      - bottom=30mm  
      - left=20mm
      - right=20mm
      - footskip=18mm
      - headsep=12mm
    include-in-header:
      - text: |
          \usepackage{setspace}
          \setstretch{1.3}
          \usepackage{array}
          \usepackage{longtable}
          \usepackage{amssymb}
          \usepackage{multirow}
          \usepackage{booktabs}
          \newcommand{\checkbox}{$\square$\ }
          \newcommand{\checkedbox}{$\blacksquare$\ }
          \newcommand{\underlinespace}[1]{\underline{\hspace{#1}}}
          \newcommand{\circlecheck}{$\bigcirc$\ }
lang: ja
version: "2025.09.06版"
header-right: "114 様式04 2025.09.06版"
---

% 手動でタイトルを作成

# 様式04: 患者安全確認表



**【発災日時】**\underlinespace{2cm}年\underlinespace{1cm}月\underlinespace{1cm}日\underlinespace{1cm}時\underlinespace{1cm}分



**【確認日時】**\underlinespace{2cm}年\underlinespace{1cm}月\underlinespace{1cm}日\underlinespace{1cm}時\underlinespace{1cm}分



**【施設名】** \underlinespace{10cm}



**【確認者】** \underlinespace{10cm}



% 発災時施設内患者状況

**\large 発災時施設内患者状況**




\checkbox 透析中患者数：\underlinespace{2cm}名



\checkbox 待機中患者数：\underlinespace{2cm}名



\checkbox その他患者数：\underlinespace{2cm}名



% 患者安全確認状況表

**\large 患者安全確認状況**




\begin{longtable}{|p{1.8cm}|p{2.2cm}|p{2cm}|p{2cm}|p{2.2cm}|p{1.8cm}|p{2cm}|}
\hline
**患者ID** & **氏名** & **状態** & **負傷の有無** & **処置内容** & **搬送要否** & **備考** \\
\hline
\endfirsthead

\hline
**患者ID** & **氏名** & **状態** & **負傷の有無** & **処置内容** & **搬送要否** & **備考** \\
\hline
\endhead

 &  & 透析中/待機/その他 & 無/軽傷/重傷 &  & 不要/要/済 &  \\
\hline
 &  & 透析中/待機/その他 & 無/軽傷/重傷 &  & 不要/要/済 &  \\
\hline
 &  & 透析中/待機/その他 & 無/軽傷/重傷 &  & 不要/要/済 &  \\
\hline
 &  & 透析中/待機/その他 & 無/軽傷/重傷 &  & 不要/要/済 &  \\
\hline
 &  & 透析中/待機/その他 & 無/軽傷/重傷 &  & 不要/要/済 &  \\
\hline
 &  & 透析中/待機/その他 & 無/軽傷/重傷 &  & 不要/要/済 &  \\
\hline
 &  & 透析中/待機/その他 & 無/軽傷/重傷 &  & 不要/要/済 &  \\
\hline
 &  & 透析中/待機/その他 & 無/軽傷/重傷 &  & 不要/要/済 &  \\
\hline
 &  & 透析中/待機/その他 & 無/軽傷/重傷 &  & 不要/要/済 &  \\
\hline
 &  & 透析中/待機/その他 & 無/軽傷/重傷 &  & 不要/要/済 &  \\
\hline
 &  & 透析中/待機/その他 & 無/軽傷/重傷 &  & 不要/要/済 &  \\
\hline
 &  & 透析中/待機/その他 & 無/軽傷/重傷 &  & 不要/要/済 &  \\
\hline
 &  & 透析中/待機/その他 & 無/軽傷/重傷 &  & 不要/要/済 &  \\
\hline
 &  & 透析中/待機/その他 & 無/軽傷/重傷 &  & 不要/要/済 &  \\
\hline
 &  & 透析中/待機/その他 & 無/軽傷/重傷 &  & 不要/要/済 &  \\
\hline
\end{longtable}



% 透析治療継続状況

**\large 透析治療継続状況**




\checkbox 透析継続可能患者：\underlinespace{2cm}名



\checkbox 透析中止患者：\underlinespace{2cm}名（理由：\underlinespace{6cm}）



\checkbox 緊急搬送患者：\underlinespace{2cm}名



% 心理的ケア実施状況

**\large 心理的ケア実施状況**




\checkbox パニック状態患者：\underlinespace{2cm}名（対応：\underlinespace{6cm}）



\checkbox 不安状態患者：\underlinespace{2cm}名（対応：\underlinespace{6cm}）



\checkbox 特別配慮必要患者：\underlinespace{2cm}名（内容：\underlinespace{6cm}）



% 集計

**\large 集計**




**総患者数：**\underlinespace{2cm}名



**安全確認済み：**\underlinespace{2cm}名（うち無事：\underlinespace{1.5cm}名、軽傷：\underlinespace{1.5cm}名、重傷：\underlinespace{1.5cm}名）



**搬送実施：**\underlinespace{2cm}名



**治療継続：**\underlinespace{2cm}名



% 特記事項

**\large 特記事項**




\underlinespace{13cm}



\underlinespace{13cm}



\underlinespace{13cm}



\underlinespace{13cm}



\underlinespace{13cm}